repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
    - id: reorder-python-imports

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --line-length=120]
      - id: ruff-format
        args: [--line-length=120]
